name: Dispatcher
on:
  push: { branches: ["main"] }
jobs:
  dispatch:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: call the other repo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          curl -X POST -H "Content-Type: application/json" -H "Authorization: Bearer ${GITHUB_TOKEN}"  --request POST --data '{"event_type": "perf_test", "client_payload": { "foo": "bar" }}' "https://github.com/vishal-19/github-actions-verification/actions/workflows/manual.yml/dispatches"

